### ISSUE TITLE
comando de testes está quebrando

### ISSUE THREAD

**Issue by gabrieldocoutos** [naveteam/react-native-nave-typescript#1]
se eu for dentro do template e rodar `yarn jest`, recebo o seguinte output:

![image](https://user-images.githubusercontent.com/40507979/117975205-d0d82780-b304-11eb-856b-18e413432287.png)

**Comment by lucasGabrielDeAA** [comment]
Eu ainda não tinha chegado a mexer na estrutura dos testes, mas já achei o problema e estou corrigindo.
