### ISSUE TITLE
Melhorar a configuração do ESLint

### ISSUE THREAD

**Issue by powilliam** [naveteam/react-native-nave-typescript#20]
Sinto que a atual configuração está bastante invasiva com warnings desnecessários no código, inclusive exigindo que tipos sejam definidos em arquivos javascript. Por exemplo, toda função precisa receber assinatura de tipo para o retorno. Não faz muito sentido, já que o Typescript é uma linguagem com inferência de tipo, então o próprio compilador, digamos, consegue identificar o retorno nesses casos.

**Comment by lucasGabrielDeAA** [comment]
Por hora vou deixar essa **issue** como `"inválida"` para podermos buscar conteúdo para melhorá-la em outros projetos e com mais pessoas da equipe
