### ISSUE TITLE
Alteração na estrutura

### ISSUE THREAD

**Issue by lucasGabrielDeAA** [naveteam/react-native-nave-typescript#34]
Em conversa com o @julianoddreis decidimos por modificar a estrutura do boilerplate, sendo assim essa e outras `pr's` que estam abertas até o momento, seguirão assim, inclusive sem revisão. Pois as mesmas passarão a integrar outro repositório e não mais este aqui. A ideia é que o boilerplate seja realmente um boilerplate e nossos novos componentes e exemplos de utilização dos mesmos se tornem parte importante de um repositório onde isto faça sentido. Não tornando nosso boilerplate uma **lib** de componentes.

Tomem nota.

**Comment by powilliam** [comment]
Eu concordo totalmente com a decisão, inclusive tenho sugestões de como poderíamos organizar o outro repositório, utilizando até a estrutura de monorepos. Isso é bem possível utilizando ferramentas como o [Lerna](https://github.com/lerna/lerna) ou até mesmo usando os [workspaces do yarn](https://classic.yarnpkg.com/en/docs/workspaces/). Dessa forma conseguiríamos delimitar o que é componente de interface, utils ou até mesmo bridges que poderão existir, usando cada pacote de acordo com a necessidade do projeto. Exemplo, o use-case de forçar atualizações, poderia estar contido somente no `@<nome>/utils`; integrações com SDK's nativas, como analytics por exemplo, dentro do pacote `@<nome>/bridges`; quem sabe um design system mobile dentro do pacote `@<nome>/ui`

**Comment by lucasGabrielDeAA** [comment]
A ideia é uma boa, realmente. Mas neste caso, a ideia deste segundo repositório é que seja baseado no front-end use-cases, é que os componentes existam em forma de playground. Com o uso do storybook, para ser mais uma fonte de consulta para nossos projetos, do que algo que nós venhamos a instalar e utilizar. Se fosse este o caso, não veria problema nenhum em passarmos a utilizar alguma estrutura como esta daí.
