### ISSUE TITLE
fiscal de segurança 🚔  

### ISSUE THREAD

**Issue by powilliam** [naveteam/react-native-nave-typescript#35]
Recentemente, quando dando uma estudada em algumas guidelines específicas da plataforma Android, me deparei com um tópico bem pontual em relação a [segurança e encriptação de dados sensíveis](https://developer.android.com/topic/security/best-practices#internal-storage), como tokens JWT etc. Achei que seria pertinente e interessante levantarmos uma discussão em relação a maneira em que o `AsyncStorage` é utilizado - vejo o uso dele para bastantes coisas na comunidade em geral, inclusive para funcionalidades extremamente sensíveis.

Como alternativa para isso, existe o [react-native-encrypted-storage](https://github.com/emeraldsanto/react-native-encrypted-storage). Basicamente consiste em uma bridge onde para o Android utiliza o pacote [Jetpack Security](https://developer.android.com/jetpack/androidx/releases/security) e, para o iOS, o [Keychain](https://developer.apple.com/documentation/security/keychain_services). Por mais que seja uma lib com pouca manutenção, ambas as implementações nativas me pareceram tranquilas, além do fato de ser recomendada nas [docs](https://reactnative.dev/docs/security#secure-storage) do próprio react native.

**Comment by julianoddreis** [comment]
Achei muito pertinente esse ponto, eu achava que era safe usar o async-storage pra guardar o token, mas pelo visto não é recomendado mesmo.
achei a [react-native-keychain](https://github.com/oblador/react-native-keychain) também, com a mesma proposta, mas parece ter um suporte mais legal, pois os mantenedores fazem parte da react native community

**Comment by lucasGabrielDeAA** [comment]
Eu também achei bastante pertinente o ponto. O quê eu levo em consideração aqui, apenas é qual dos dois apresentados possui menor impacto em questão de performance e estruturação. Vocês já trabalharam com tais `libs`?
O motivo da minha questão se dá pelo simples motivo, como vamos fazer uma `"limpa"` no **boilerplate** para deixá-lo com cara de um template mesmo, seria interessante uma lib que não fosse tão "pesada" com uma dinâmica parecida com o próprio `async-atorage`.

Até o momento o quê me chamou a atenção entre elas é, uma possui a utilização bem parecida com o quê já utilizamos, e a outra tem a questão da comunidade mantenedora. Quais outros pontos vocês veem?

**Comment by powilliam** [comment]
A única lib que cheguei a utilizar para isso, foi o [Secure Storage](https://docs.expo.dev/versions/latest/sdk/securestore/), há bastante tempo.

Eu dei uma olhada na que o Juliano mandou. Eu achei bem interessante. Mas as issues da lib me deixaram preocupado, já que tem bastante gente reportando que não funciona/crasha na variante de release de x dispositivos etc, fora que pelo menos para o lado nativo do Android, não chega a utilizar os pacotes recentes e recomendados, o tal Jetpack.

Em relação a que eu cheguei a recomendar, o que me preocupa é a manutenção dela. Faz muito tempo que não recebe atualizações e também não existem issues p caso precisemos ir atrás de alguma solução para algum problema. Acho que poderíamos investir um tempo dando uma olhada
